### ISSUE TITLE
install header files?

### ISSUE THREAD

**Issue by codehero** [raptor/clip2tri#4]
Hi first thank you for sharing your work. I was wondering if you could add header file installation to the CMake script?

**Comment by raptor** [comment]
Hi,

What exactly do you mean by 'header file installation' ?

Thanks!

**Comment by codehero** [comment]
Sorry, what I meant was the .h and .hpp files that generally get installed into the /usr/include directory.

**Comment by raptor** [comment]
Done in commit f62a734d22733814b8a970ed8a68a4d94c24fa5f
